import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Serif_Text, Overpass } from "next/font/google";
import "./globals.css";

const dmSerifText = DM_Serif_Text({
  weight: ["400"],
  variable: "--font-serif",
  subsets: ["latin"],
});

const overpass = Overpass({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSerifText.variable} ${overpass.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
